package-lock.json
routes/participant-consent-form/participant-consent-form.njk

This fixes the error that occurs when you hit continue from /participant-consent-form:
Not sure why the package-lock.json changed...

Added a hidden input field with csrf token to our new template

---

assets/scss/_forms.scss

make form wider on larger screen

---

routes/agreement-1/agreement-1.controller.js
routes/landing-page/landing-page.controller.js
routes/questions-1/questions-1.controller.js
utils/route.helpers.js
utils/route.helpers.spec.js

Added the query params to the routes

---

routes/agreement-1/agreement-1-fr.njk

Added default value functionality to template

---

assets/scss/_forms.scss
public/js/toggle-area.js
routes/questions-1/questions-1.njk

fix spacing in disclosure area

---

locales/en.json
routes/questions-1/schema.js

add validation rules for illegal selections

---

views/macros/default-value.njk

re #63 
So newlines in the `defaultValues` macro were causing unwanted spaces in the agreement template. So we have to write part of the macro all in one line. 😞 
[old](https://simplify-privacy-statements-v2.herokuapp.com/questions-1?researcher_name=Steve%20Astels&researcher_phone=555-5555&researcher_email=sastels%40gmail.com&is_with_partner=Yes&partner_department_name=Royal%20Canadian%20Mounted%20Police&partner_department_acronym=RCMP&partner_department_authority=Policy%2012.3B&research_method=Usability%20testing&research_goal=Create%20an%20online%20tool%20that%20will%20make%20it%20easier%20for%20Veterans%20to%20determine%20which%20VAC%20services%20are%20relevant%20to%20them&session_activity=Complete%20tasks%20with%20our%20prototype%20software%20and%20ask%20you%20to%20describe%20your%20th …

Remove extra spaces

---

assets/scss/_forms.scss
locales/en.json
locales/fr.json
routes/translations-1/translations-1.njk
views/base.njk
views/macros/buttons.njk

Added skip button to translations page

---

app.json
config/csp.config.js

works locally!
Also, I pushed this branch to production temporarily 😬 
You can go to
https://privacy-statements.cds.alpha.canada.ca
and watch the stats at
https://analytics.google.com/analytics/web/#/realtime/rt-overview/a102484926w211850887p203342334

csp rules for GA

---

routes/agreement-1/agreement-1.controller.js
routes/agreement-2/agreement-2.controller.js

Closes #59 
Technically I replaced the "Symbol of the Government of Canada" - the flag thing at the top. The wordmark is the thing at the bottom. I think that was the intention.

Added in placeholder for flag symbol

---

assets/scss/_forms.scss
assets/scss/components/_multiple-choice.scss
routes/questions-1/questions-1.njk
views/macros/radios.njk

Add ability to display hint text under radio button questions

Hint text radios fix

---

routes/agreement-1/agreement-1.controller.js
routes/agreement-2/agreement-2.controller.js

Closes #92 
@keithiopia Let me know if there is a more useful website I could link to

Swapped in placeholder for wordmark, added links to the FIP website

---

routes/translations-1/translations-1.njk
views/base.njk
views/macros/translation.njk

Fix for "switch language on translations page" bug

---

routes/agreement-1/agreement-1-en.njk
routes/agreement-1/agreement-1-fr.njk
routes/agreement-1/agreement-1.controller.js

Added hidden div to mark start of agreement

---

a11y.json

added our new pages to the automated a11y scanner.
https://github.com/cds-snc/simplify-privacy-statements-V2/actions?workflow=a11y-scanning

Add pages to a11y scanner

---

routes/questions-1/questions-1.controller.js

fixes #110 
The query params we accidentally removed from the data in #99. It's almost like we should be doing proper testing...

restore query params to question data

---

locales/en.json
routes/agreement-1/agreement-1-en.njk
routes/agreement-1/agreement-1-fr.njk
routes/questions-1/questions-1.njk

resolves #107 
Add a "will you be sharing recording" question instead of assuming that the researcher will share recordings with another department.
Make corresponding changes to the agreements.

add 'will you share recording' question

---

locales/en.json
locales/fr.json
routes/feedback/feedback.controller.js
routes/feedback/feedback.njk
utils/notify.helpers.js

fixes #114 
Will run if Notify env vars not present.

works if Notify not set up

---

locales/en.json
routes/questions-1/schema.js

don't allow cds-snc.ca email addresses

---

public/js/toggle-area.js
views/base.njk

Get hidden questions working on IE / Edge

---

locales/en.json
locales/fr.json
views/_includes/phaseBanner.njk

https://trello.com/c/d0Msx9nV/92-update-product-banner-to-beta

Changed ALPHA -> BETA

---

routes/agreement-1/agreement-1-fr.njk

Plain language edit in French to mirror the plain language edit Keith did in English (https://github.com/cds-snc/simplify-privacy-statements-V2/pull/152/files)

French plain language edit

---

views/base.njk
views/macros/input-select.njk

Adds a select input. Needed for work on #169.

Add a select input macro

---

locales/en.json

Update to Landing page title

---

.github/workflows/tf_apply_production.yml
.github/workflows/tf_plan_production.yml
terragrunt/env/production/terragrunt.hcl

Added GitHub Plan and Apply workflows that will be used to manage our production infrastructure

feat: Added Terraform Plan and Apply workflow

---

terragrunt/aws/app/inputs.tf
terragrunt/aws/app/lambda.tf
terragrunt/aws/efs/outputs.tf
terragrunt/env/production/app/terragrunt.hcl

Still getting permission denied errors for mounting the file system. added policy to allow lambda module to access EFS

added lambda vpc access

---

terragrunt/aws/app/lambda.tf

Removed EFS full access to see if it is needed

removed efs full access

---

terragrunt/env/production/vpc/.terraform.lock.hcl

lockfile update

---

terragrunt/aws/vpc/outputs.tf

Adding security group ID variables for EFS and Lambda

added new sg variables

---

.github/workflows/tf_apply_production.yml
.github/workflows/tf_plan_production.yml
terragrunt/aws/cloudfront/certificates.tf
terragrunt/aws/cloudfront/cloudfront.tf
terragrunt/aws/cloudfront/iam.tf
terragrunt/aws/cloudfront/inputs.tf
terragrunt/aws/cloudfront/locals.tf
terragrunt/aws/cloudfront/s3.tf
terragrunt/aws/cloudfront/waf.tf
terragrunt/env/common/common_variables.tf
terragrunt/env/common/provider.tf
terragrunt/env/production/cloudfront/.terraform.lock.hcl
terragrunt/env/production/cloudfront/terragrunt.hcl
terragrunt/env/production/hosted_zone/.terraform.lock.hcl
terragrunt/env/terragrunt.hcl

Cloudfront module and config that creates the CloudFront distribution and Web Application Firewall Access Control List (WAF ACL).

added cloudfront module

---

config/csp.config.js

updated CSP script src

---

app.js

fix spelling mistake

---

terragrunt/aws/cloudfront/certificates.tf
terragrunt/aws/cloudfront/cloudfront.tf
terragrunt/aws/cloudfront/route53.tf

Updated certificate alt name and cloudfront alias. Created A record for FR

added domain name to alias, created A record

---

terragrunt/aws/cloudfront/certificates.tf

Created a French DNS Validation resource

added fr validation resource

---

package-lock.json
package.json

Moved aws-lambda-ric from dockerfile over to package.json

moved dependency into package.json

---

locales/en.json
locales/fr.json
routes/agreement-1/agreement-1-en.njk
routes/agreement-1/agreement-1-fr.njk
routes/landing-page/landing-page.njk

Straight content updates that didn't need content review. Adding missing translations etc.

Content updates not waiting on content review
